### ISSUE TITLE
How to use with julienschmidt/httprouter?

### ISSUE THREAD

**Issue by leadinglocally** [auth0/auth0-golang#1]
How do I use this with one of the most popular (production) http router packages:

https://github.com/julienschmidt/httprouter#where-can-i-find-middleware-x

Is it possible?

**Comment by mgonto** [comment]
Hey,

From what I see, that httprouter expects a function with the Response, Request signature as the middleware. That means that you can just use the `CheckJWT` endpoint from `go-jwt-middleware` to make it work :).

Check [this martini example](https://github.com/auth0/go-jwt-middleware/blob/master/examples/martini-example/main.go#L27) to see how you'd add the go-jwt-middleware to work with httprouter :).

Let me know if that helsp!

Cheers

**Comment by leadinglocally** [comment]
The httprouter only accepts two parameters per handlefunc, so it wont accept the additional middleware function like Martini does.

**Comment by natdm** [comment]
Were you ever able to get this to work?

**Comment by rkiesler1** [comment]
Anyone ever got jwtMiddleware.CheckJWT to work with julienschmidt/httprouter?
